### ISSUE TITLE
音楽再生する機能をつけるよっ

### ISSUE THREAD

**Issue by kemokemo** [kemokemo/kuronan-dash#2]
やっぱりゲームでBGMは大事だよね！方法は以下のいずれかが良さそうだよ！

* [go-mp3](https://github.com/hajimehoshi/go-mp3)と[oto](https://github.com/hajimehoshi/oto)を[AbortableCopy](https://gist.github.com/KemoKemo/ab3776224e7557b389ed07595546f78c)で繋いで再生
* [ebiten/audio](https://github.com/hajimehoshi/ebiten/tree/master/audio)を使った再生 - [サンプル](https://github.com/hajimehoshi/ebiten/blob/master/examples/audio/main.go)

**Comment by kemokemo** [comment]
[サンプル](https://github.com/hajimehoshi/ebiten/blob/master/examples/audio/main.go)はサンプリングレート固定だったけど、今やgo-mp3のNewDecoderで生成したDecoderのSampleRate()で取得できる！

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/blob/master/examples/wav/main.go より簡単な再生サンプルを作りましたので、もしよろしければご参照ください。

**Comment by kemokemo** [comment]
hoshiさん、どうもありがとうございます！めっちゃ参考になります！！
早速実行してみました。
![image](https://user-images.githubusercontent.com/12206485/29046948-a08145e8-7c04-11e7-8768-49bb5e916a8e.png)

そう、そうなんですよ！ゲーム内でキャラが攻撃した時とかのSEの再生方法どうしよって思ってたんですが、まさにこれです 😄

**Comment by kemokemo** [comment]
JukeBoxの仕組みができた。以下のように使う。複数の曲をいろいろ変えたいときに便利だと思う。

1. 音楽名と音楽ファイルパスをInsertDiscsでインプット
1. SelectDiscしてebitenのupdate関数内でPlay実行し続ける
1. 画面が変わってBGMが変わるときは、またSelectDiscで曲を選び直してPlay！

別途「ebitenと一緒に使うと美味しいライブラリ」としてくくりだした方が良いだろうか。。  
そうするにしてもtestコードが少なすぎると思う。反省。。。
